In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

In [3]:
mail_data = pd.read_csv('/content/mail_data.csv')

In [4]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

Now we can see the output labels are categorical strings hence need to convert into 0s 1s

In [5]:
mail_data = mail_data.replace({'Category':{'ham':0,'spam':1}})

/tmp/ipykernel_346/4069890194.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  mail_data = mail_data.replace({'Category':{'ham':0,'spam':1}})

In [6]:
mail_data.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [8]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [9]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

# Load once
port_stem = PorterStemmer()
stop_words = set(stopwords.words('english'))  # load once

def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if word not in stop_words]
    return ' '.join(stemmed_content)

  #Applying to our dataframe
mail_data['Message'] = mail_data['Message'].apply(stemming)

In [10]:
mail_data.head()

   Category                                            Message
0         0  go jurong point crazi avail bugi n great world...
1         0                              ok lar joke wif u oni
2         1  free entri wkli comp win fa cup final tkt st m...
3         0                u dun say earli hor u c alreadi say
4         0               nah think goe usf live around though

In [11]:
#Now converting this text data into vector form so it can be fed to model
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
vectorizer = TfidfVectorizer()

In [13]:
from sklearn.model_selection import train_test_split

X = mail_data['Message']
Y = mail_data['Category']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [14]:
print(X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36030 stored elements and shape (4457, 5630)>
  Coords	Values
  (0, 5159)	0.5432602033614844
  (0, 4851)	0.33507605609811486
  (0, 2704)	0.6295382112335581
  (0, 2995)	0.443028248162827
  (1, 2043)	0.6018316698048912
  (1, 5197)	0.4036983926522384
  (1, 597)	0.5850786562946425
  (1, 1153)	0.3640181519351901
  (2, 5114)	0.36340008681999314
  (2, 964)	0.2886380596011352
  (2, 4289)	0.3175599597052956
  (2, 58)	0.27171983259059806
  (2, 4122)	0.36340008681999314
  (2, 3484)	0.36340008681999314
  (2, 2617)	0.34648185980945595
  (2, 5519)	0.32516741451477776
  (2, 3664)	0.34648185980945595
  (3, 964)	0.3783221289227234
  (3, 5220)	0.35927316625093886
  (3, 5279)	0.40779995519376544
  (3, 1103)	0.3048330072609444
  (3, 3583)	0.28033044570845034
  (3, 5427)	0.28345645077678
  (3, 3758)	0.27957608616629226
  (3, 929)	0.30027285041546553
  :	:
  (4454, 323)	0.2991193838720389
  (4454, 3492)	0.252001602193042
  (4454, 720)	0.252001602193042
  (4454, 1250)	0.2991193838720389
  (4454, 4805)	0.32352087587146866
  (4455, 1969)	0.2973442417526907
  (4455, 3245)	0.43793598297523884
  (4455, 2630)	0.3724777450427359
  (4455, 2489)	0.5390077950085265
  (4455, 5287)	0.5390077950085265
  (4456, 4851)	0.13437151216351914
  (4456, 1897)	0.11100538708125414
  (4456, 1144)	0.12786699838005247
  (4456, 3375)	0.13852398327128065
  (4456, 368)	0.14534087210081942
  (4456, 4224)	0.17107726825696226
  (4456, 3221)	0.3458247078708562
  (4456, 5546)	0.18505817437458713
  (4456, 5251)	0.39205506862377476
  (4456, 1482)	0.19350671778646336
  (4456, 1477)	0.1841452584562568
  (4456, 5250)	0.2615162059757618
  (4456, 154)	0.24542857336778753
  (4456, 3585)	0.5485713567151281
  (4456, 2553)	0.27428567835756407

In [15]:
model = LogisticRegression()

In [16]:
model.fit(X_train,Y_train)

LogisticRegression()

In [17]:
#Evaluating on Training data
X_train_prediction = model.predict(X_train)
X_train_accuracy = accuracy_score(Y_train,X_train_prediction)
print(X_train_accuracy)

0.9726273277989679

In [18]:
#Evaluating on test data
X_test_prediction = model.predict(X_test)
X_test_accuracy = accuracy_score(Y_test,X_test_prediction)
print(X_test_accuracy)

0.9551569506726457

In [ ]:
#Testing our model
input_mail = input("Enter any mail:")
news_vectorized = vectorizer.transform([input_mail])

prediction = model.predict(news_vectorized)
print(prediction)